/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotersIndexRouteImport } from './routes/voters/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CompetitionIndexRouteImport } from './routes/competition/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as PaymentsSuccessRouteImport } from './routes/payments/success'
import { Route as PaymentsFailureRouteImport } from './routes/payments/failure'
import { Route as DashboardSectionRouteImport } from './routes/dashboard/$section'
import { Route as CompetitionIdRouteImport } from './routes/competition/$id'
import { Route as AuthIdRouteImport } from './routes/auth/$id'
import { Route as AdminWinnersRouteImport } from './routes/admin/winners'
import { Route as AdminVotesBoostRouteImport } from './routes/admin/votes-boost'
import { Route as AdminProfilesRouteImport } from './routes/admin/profiles'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminContestsIndexRouteImport } from './routes/admin/contests/index'
import { Route as AdminContestsCreateRouteImport } from './routes/admin/contests/create'
import { Route as AdminContestsIdLeaderboardRouteImport } from './routes/admin/contests/$id.leaderboard'
import { Route as AdminContestsIdEditRouteImport } from './routes/admin/contests/$id.edit'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotersIndexRoute = VotersIndexRouteImport.update({
  id: '/voters/',
  path: '/voters/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionIndexRoute = CompetitionIndexRouteImport.update({
  id: '/competition/',
  path: '/competition/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFailureRoute = PaymentsFailureRouteImport.update({
  id: '/payments/failure',
  path: '/payments/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/dashboard/$section',
  path: '/dashboard/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionIdRoute = CompetitionIdRouteImport.update({
  id: '/competition/$id',
  path: '/competition/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdRoute = AuthIdRouteImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVotesBoostRoute = AdminVotesBoostRouteImport.update({
  id: '/votes-boost',
  path: '/votes-boost',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsIndexRoute = AdminContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsCreateRoute = AdminContestsCreateRouteImport.update({
  id: '/contests/create',
  path: '/contests/create',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsIdLeaderboardRoute =
  AdminContestsIdLeaderboardRouteImport.update({
    id: '/contests/$id/leaderboard',
    path: '/contests/$id/leaderboard',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContestsIdEditRoute = AdminContestsIdEditRouteImport.update({
  id: '/contests/$id/edit',
  path: '/contests/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/rules': typeof RulesRoute
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/votes-boost': typeof AdminVotesBoostRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auth/$id': typeof AuthIdRoute
  '/competition/$id': typeof CompetitionIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/competition': typeof CompetitionIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/voters': typeof VotersIndexRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/admin/contests': typeof AdminContestsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/contests/$id/edit': typeof AdminContestsIdEditRoute
  '/admin/contests/$id/leaderboard': typeof AdminContestsIdLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/rules': typeof RulesRoute
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/votes-boost': typeof AdminVotesBoostRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auth/$id': typeof AuthIdRoute
  '/competition/$id': typeof CompetitionIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin': typeof AdminIndexRoute
  '/competition': typeof CompetitionIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/voters': typeof VotersIndexRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/admin/contests': typeof AdminContestsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/contests/$id/edit': typeof AdminContestsIdEditRoute
  '/admin/contests/$id/leaderboard': typeof AdminContestsIdLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/rules': typeof RulesRoute
  '/winners': typeof WinnersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/votes-boost': typeof AdminVotesBoostRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auth/$id': typeof AuthIdRoute
  '/competition/$id': typeof CompetitionIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/competition/': typeof CompetitionIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/voters/': typeof VotersIndexRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/admin/contests/': typeof AdminContestsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/contests/$id/edit': typeof AdminContestsIdEditRoute
  '/admin/contests/$id/leaderboard': typeof AdminContestsIdLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/rules'
    | '/winners'
    | '/admin/analytics'
    | '/admin/leaderboard'
    | '/admin/payments'
    | '/admin/profiles'
    | '/admin/votes-boost'
    | '/admin/winners'
    | '/auth/$id'
    | '/competition/$id'
    | '/dashboard/$section'
    | '/payments/failure'
    | '/payments/success'
    | '/profile/$id'
    | '/admin/'
    | '/competition'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/voters'
    | '/admin/contests/create'
    | '/admin/contests'
    | '/admin/users'
    | '/admin/contests/$id/edit'
    | '/admin/contests/$id/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/contact'
    | '/faq'
    | '/rules'
    | '/winners'
    | '/admin/analytics'
    | '/admin/leaderboard'
    | '/admin/payments'
    | '/admin/profiles'
    | '/admin/votes-boost'
    | '/admin/winners'
    | '/auth/$id'
    | '/competition/$id'
    | '/dashboard/$section'
    | '/payments/failure'
    | '/payments/success'
    | '/profile/$id'
    | '/admin'
    | '/competition'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/voters'
    | '/admin/contests/create'
    | '/admin/contests'
    | '/admin/users'
    | '/admin/contests/$id/edit'
    | '/admin/contests/$id/leaderboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/rules'
    | '/winners'
    | '/admin/analytics'
    | '/admin/leaderboard'
    | '/admin/payments'
    | '/admin/profiles'
    | '/admin/votes-boost'
    | '/admin/winners'
    | '/auth/$id'
    | '/competition/$id'
    | '/dashboard/$section'
    | '/payments/failure'
    | '/payments/success'
    | '/profile/$id'
    | '/admin/'
    | '/competition/'
    | '/dashboard/'
    | '/leaderboard/'
    | '/onboarding/'
    | '/voters/'
    | '/admin/contests/create'
    | '/admin/contests/'
    | '/admin/users/'
    | '/admin/contests/$id/edit'
    | '/admin/contests/$id/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  RulesRoute: typeof RulesRoute
  WinnersRoute: typeof WinnersRoute
  AuthIdRoute: typeof AuthIdRoute
  CompetitionIdRoute: typeof CompetitionIdRoute
  DashboardSectionRoute: typeof DashboardSectionRoute
  PaymentsFailureRoute: typeof PaymentsFailureRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
  ProfileIdRoute: typeof ProfileIdRoute
  CompetitionIndexRoute: typeof CompetitionIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  VotersIndexRoute: typeof VotersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voters/': {
      id: '/voters/'
      path: '/voters'
      fullPath: '/voters'
      preLoaderRoute: typeof VotersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/': {
      id: '/competition/'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/failure': {
      id: '/payments/failure'
      path: '/payments/failure'
      fullPath: '/payments/failure'
      preLoaderRoute: typeof PaymentsFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/dashboard/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition/$id': {
      id: '/competition/$id'
      path: '/competition/$id'
      fullPath: '/competition/$id'
      preLoaderRoute: typeof CompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/votes-boost': {
      id: '/admin/votes-boost'
      path: '/votes-boost'
      fullPath: '/admin/votes-boost'
      preLoaderRoute: typeof AdminVotesBoostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests/': {
      id: '/admin/contests/'
      path: '/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AdminContestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests/create': {
      id: '/admin/contests/create'
      path: '/contests/create'
      fullPath: '/admin/contests/create'
      preLoaderRoute: typeof AdminContestsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests/$id/leaderboard': {
      id: '/admin/contests/$id/leaderboard'
      path: '/contests/$id/leaderboard'
      fullPath: '/admin/contests/$id/leaderboard'
      preLoaderRoute: typeof AdminContestsIdLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests/$id/edit': {
      id: '/admin/contests/$id/edit'
      path: '/contests/$id/edit'
      fullPath: '/admin/contests/$id/edit'
      preLoaderRoute: typeof AdminContestsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminVotesBoostRoute: typeof AdminVotesBoostRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContestsCreateRoute: typeof AdminContestsCreateRoute
  AdminContestsIndexRoute: typeof AdminContestsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminContestsIdEditRoute: typeof AdminContestsIdEditRoute
  AdminContestsIdLeaderboardRoute: typeof AdminContestsIdLeaderboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminVotesBoostRoute: AdminVotesBoostRoute,
  AdminWinnersRoute: AdminWinnersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContestsCreateRoute: AdminContestsCreateRoute,
  AdminContestsIndexRoute: AdminContestsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminContestsIdEditRoute: AdminContestsIdEditRoute,
  AdminContestsIdLeaderboardRoute: AdminContestsIdLeaderboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  RulesRoute: RulesRoute,
  WinnersRoute: WinnersRoute,
  AuthIdRoute: AuthIdRoute,
  CompetitionIdRoute: CompetitionIdRoute,
  DashboardSectionRoute: DashboardSectionRoute,
  PaymentsFailureRoute: PaymentsFailureRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
  ProfileIdRoute: ProfileIdRoute,
  CompetitionIndexRoute: CompetitionIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  VotersIndexRoute: VotersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
