/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WinnersRouteImport } from './routes/winners'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VotersIndexRouteImport } from './routes/voters/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LeaderboardIndexRouteImport } from './routes/leaderboard/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as PaymentsSuccessRouteImport } from './routes/payments/success'
import { Route as PaymentsFailureRouteImport } from './routes/payments/failure'
import { Route as DashboardSectionRouteImport } from './routes/dashboard/$section'
import { Route as AuthIdRouteImport } from './routes/auth/$id'
import { Route as AdminWinnersRouteImport } from './routes/admin/winners'
import { Route as AdminVotesBoostRouteImport } from './routes/admin/votes-boost'
import { Route as AdminProfilesRouteImport } from './routes/admin/profiles'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as PublicRulesRouteImport } from './routes/_public/rules'
import { Route as PublicFaqRouteImport } from './routes/_public/faq'
import { Route as PublicContactRouteImport } from './routes/_public/contact'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminContestsIndexRouteImport } from './routes/admin/contests/index'
import { Route as PublicCompetitionsIndexRouteImport } from './routes/_public/competitions/index'
import { Route as DashboardCompetitionsSlugRouteImport } from './routes/dashboard/competitions.$slug'
import { Route as AdminContestsCreateRouteImport } from './routes/admin/contests/create'
import { Route as PublicCompetitionsSlugRouteImport } from './routes/_public/competitions/$slug'
import { Route as AdminContestsIdLeaderboardRouteImport } from './routes/admin/contests/$id.leaderboard'
import { Route as AdminContestsIdEditRouteImport } from './routes/admin/contests/$id.edit'

const WinnersRoute = WinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VotersIndexRoute = VotersIndexRouteImport.update({
  id: '/voters/',
  path: '/voters/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardIndexRoute = LeaderboardIndexRouteImport.update({
  id: '/leaderboard/',
  path: '/leaderboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsSuccessRoute = PaymentsSuccessRouteImport.update({
  id: '/payments/success',
  path: '/payments/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsFailureRoute = PaymentsFailureRouteImport.update({
  id: '/payments/failure',
  path: '/payments/failure',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/dashboard/$section',
  path: '/dashboard/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdRoute = AuthIdRouteImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWinnersRoute = AdminWinnersRouteImport.update({
  id: '/winners',
  path: '/winners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVotesBoostRoute = AdminVotesBoostRouteImport.update({
  id: '/votes-boost',
  path: '/votes-boost',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicRulesRoute = PublicRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContestsIndexRoute = AdminContestsIndexRouteImport.update({
  id: '/contests/',
  path: '/contests/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicCompetitionsIndexRoute = PublicCompetitionsIndexRouteImport.update({
  id: '/competitions/',
  path: '/competitions/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const DashboardCompetitionsSlugRoute =
  DashboardCompetitionsSlugRouteImport.update({
    id: '/dashboard/competitions/$slug',
    path: '/dashboard/competitions/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminContestsCreateRoute = AdminContestsCreateRouteImport.update({
  id: '/contests/create',
  path: '/contests/create',
  getParentRoute: () => AdminRoute,
} as any)
const PublicCompetitionsSlugRoute = PublicCompetitionsSlugRouteImport.update({
  id: '/competitions/$slug',
  path: '/competitions/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AdminContestsIdLeaderboardRoute =
  AdminContestsIdLeaderboardRouteImport.update({
    id: '/contests/$id/leaderboard',
    path: '/contests/$id/leaderboard',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContestsIdEditRoute = AdminContestsIdEditRouteImport.update({
  id: '/contests/$id/edit',
  path: '/contests/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/winners': typeof WinnersRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/rules': typeof PublicRulesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/votes-boost': typeof AdminVotesBoostRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auth/$id': typeof AuthIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/voters': typeof VotersIndexRoute
  '/competitions/$slug': typeof PublicCompetitionsSlugRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/dashboard/competitions/$slug': typeof DashboardCompetitionsSlugRoute
  '/competitions': typeof PublicCompetitionsIndexRoute
  '/admin/contests': typeof AdminContestsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/contests/$id/edit': typeof AdminContestsIdEditRoute
  '/admin/contests/$id/leaderboard': typeof AdminContestsIdLeaderboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/winners': typeof WinnersRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/rules': typeof PublicRulesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/votes-boost': typeof AdminVotesBoostRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auth/$id': typeof AuthIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/leaderboard': typeof LeaderboardIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/voters': typeof VotersIndexRoute
  '/competitions/$slug': typeof PublicCompetitionsSlugRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/dashboard/competitions/$slug': typeof DashboardCompetitionsSlugRoute
  '/competitions': typeof PublicCompetitionsIndexRoute
  '/admin/contests': typeof AdminContestsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/contests/$id/edit': typeof AdminContestsIdEditRoute
  '/admin/contests/$id/leaderboard': typeof AdminContestsIdLeaderboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/admin': typeof AdminRouteWithChildren
  '/winners': typeof WinnersRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/rules': typeof PublicRulesRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/votes-boost': typeof AdminVotesBoostRoute
  '/admin/winners': typeof AdminWinnersRoute
  '/auth/$id': typeof AuthIdRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/payments/failure': typeof PaymentsFailureRoute
  '/payments/success': typeof PaymentsSuccessRoute
  '/profile/$id': typeof ProfileIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/leaderboard/': typeof LeaderboardIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/voters/': typeof VotersIndexRoute
  '/_public/competitions/$slug': typeof PublicCompetitionsSlugRoute
  '/admin/contests/create': typeof AdminContestsCreateRoute
  '/dashboard/competitions/$slug': typeof DashboardCompetitionsSlugRoute
  '/_public/competitions/': typeof PublicCompetitionsIndexRoute
  '/admin/contests/': typeof AdminContestsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/contests/$id/edit': typeof AdminContestsIdEditRoute
  '/admin/contests/$id/leaderboard': typeof AdminContestsIdLeaderboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/winners'
    | '/contact'
    | '/faq'
    | '/rules'
    | '/admin/analytics'
    | '/admin/leaderboard'
    | '/admin/payments'
    | '/admin/profiles'
    | '/admin/votes-boost'
    | '/admin/winners'
    | '/auth/$id'
    | '/dashboard/$section'
    | '/payments/failure'
    | '/payments/success'
    | '/profile/$id'
    | '/admin/'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/voters'
    | '/competitions/$slug'
    | '/admin/contests/create'
    | '/dashboard/competitions/$slug'
    | '/competitions'
    | '/admin/contests'
    | '/admin/users'
    | '/admin/contests/$id/edit'
    | '/admin/contests/$id/leaderboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/winners'
    | '/contact'
    | '/faq'
    | '/rules'
    | '/admin/analytics'
    | '/admin/leaderboard'
    | '/admin/payments'
    | '/admin/profiles'
    | '/admin/votes-boost'
    | '/admin/winners'
    | '/auth/$id'
    | '/dashboard/$section'
    | '/payments/failure'
    | '/payments/success'
    | '/profile/$id'
    | '/admin'
    | '/dashboard'
    | '/leaderboard'
    | '/onboarding'
    | '/voters'
    | '/competitions/$slug'
    | '/admin/contests/create'
    | '/dashboard/competitions/$slug'
    | '/competitions'
    | '/admin/contests'
    | '/admin/users'
    | '/admin/contests/$id/edit'
    | '/admin/contests/$id/leaderboard'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/$'
    | '/admin'
    | '/winners'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/rules'
    | '/admin/analytics'
    | '/admin/leaderboard'
    | '/admin/payments'
    | '/admin/profiles'
    | '/admin/votes-boost'
    | '/admin/winners'
    | '/auth/$id'
    | '/dashboard/$section'
    | '/payments/failure'
    | '/payments/success'
    | '/profile/$id'
    | '/admin/'
    | '/dashboard/'
    | '/leaderboard/'
    | '/onboarding/'
    | '/voters/'
    | '/_public/competitions/$slug'
    | '/admin/contests/create'
    | '/dashboard/competitions/$slug'
    | '/_public/competitions/'
    | '/admin/contests/'
    | '/admin/users/'
    | '/admin/contests/$id/edit'
    | '/admin/contests/$id/leaderboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRouteWithChildren
  WinnersRoute: typeof WinnersRoute
  AuthIdRoute: typeof AuthIdRoute
  DashboardSectionRoute: typeof DashboardSectionRoute
  PaymentsFailureRoute: typeof PaymentsFailureRoute
  PaymentsSuccessRoute: typeof PaymentsSuccessRoute
  ProfileIdRoute: typeof ProfileIdRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LeaderboardIndexRoute: typeof LeaderboardIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  VotersIndexRoute: typeof VotersIndexRoute
  DashboardCompetitionsSlugRoute: typeof DashboardCompetitionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/winners': {
      id: '/winners'
      path: '/winners'
      fullPath: '/winners'
      preLoaderRoute: typeof WinnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voters/': {
      id: '/voters/'
      path: '/voters'
      fullPath: '/voters'
      preLoaderRoute: typeof VotersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard/': {
      id: '/leaderboard/'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/success': {
      id: '/payments/success'
      path: '/payments/success'
      fullPath: '/payments/success'
      preLoaderRoute: typeof PaymentsSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/failure': {
      id: '/payments/failure'
      path: '/payments/failure'
      fullPath: '/payments/failure'
      preLoaderRoute: typeof PaymentsFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/dashboard/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/winners': {
      id: '/admin/winners'
      path: '/winners'
      fullPath: '/admin/winners'
      preLoaderRoute: typeof AdminWinnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/votes-boost': {
      id: '/admin/votes-boost'
      path: '/votes-boost'
      fullPath: '/admin/votes-boost'
      preLoaderRoute: typeof AdminVotesBoostRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/rules': {
      id: '/_public/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof PublicRulesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests/': {
      id: '/admin/contests/'
      path: '/contests'
      fullPath: '/admin/contests'
      preLoaderRoute: typeof AdminContestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/competitions/': {
      id: '/_public/competitions/'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof PublicCompetitionsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/dashboard/competitions/$slug': {
      id: '/dashboard/competitions/$slug'
      path: '/dashboard/competitions/$slug'
      fullPath: '/dashboard/competitions/$slug'
      preLoaderRoute: typeof DashboardCompetitionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contests/create': {
      id: '/admin/contests/create'
      path: '/contests/create'
      fullPath: '/admin/contests/create'
      preLoaderRoute: typeof AdminContestsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/competitions/$slug': {
      id: '/_public/competitions/$slug'
      path: '/competitions/$slug'
      fullPath: '/competitions/$slug'
      preLoaderRoute: typeof PublicCompetitionsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/admin/contests/$id/leaderboard': {
      id: '/admin/contests/$id/leaderboard'
      path: '/contests/$id/leaderboard'
      fullPath: '/admin/contests/$id/leaderboard'
      preLoaderRoute: typeof AdminContestsIdLeaderboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contests/$id/edit': {
      id: '/admin/contests/$id/edit'
      path: '/contests/$id/edit'
      fullPath: '/admin/contests/$id/edit'
      preLoaderRoute: typeof AdminContestsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicRulesRoute: typeof PublicRulesRoute
  PublicCompetitionsSlugRoute: typeof PublicCompetitionsSlugRoute
  PublicCompetitionsIndexRoute: typeof PublicCompetitionsIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicRulesRoute: PublicRulesRoute,
  PublicCompetitionsSlugRoute: PublicCompetitionsSlugRoute,
  PublicCompetitionsIndexRoute: PublicCompetitionsIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminVotesBoostRoute: typeof AdminVotesBoostRoute
  AdminWinnersRoute: typeof AdminWinnersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContestsCreateRoute: typeof AdminContestsCreateRoute
  AdminContestsIndexRoute: typeof AdminContestsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminContestsIdEditRoute: typeof AdminContestsIdEditRoute
  AdminContestsIdLeaderboardRoute: typeof AdminContestsIdLeaderboardRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminVotesBoostRoute: AdminVotesBoostRoute,
  AdminWinnersRoute: AdminWinnersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContestsCreateRoute: AdminContestsCreateRoute,
  AdminContestsIndexRoute: AdminContestsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminContestsIdEditRoute: AdminContestsIdEditRoute,
  AdminContestsIdLeaderboardRoute: AdminContestsIdLeaderboardRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRouteWithChildren,
  WinnersRoute: WinnersRoute,
  AuthIdRoute: AuthIdRoute,
  DashboardSectionRoute: DashboardSectionRoute,
  PaymentsFailureRoute: PaymentsFailureRoute,
  PaymentsSuccessRoute: PaymentsSuccessRoute,
  ProfileIdRoute: ProfileIdRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LeaderboardIndexRoute: LeaderboardIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  VotersIndexRoute: VotersIndexRoute,
  DashboardCompetitionsSlugRoute: DashboardCompetitionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
